#!/bin/bash

cmd=$1

LOG=/var/log/mpdctrl.log
exec &>> $LOG
echo $(date +"%F %T") $*

MODEFILE=/etc/mpdctrl.mode
test -f $MODEFILE || echo -n play >$MODEFILE
mode=$(cat $MODEFILE)

case $cmd in
toggleplay)
    mpc toggle
    ;;
resetchannels)
    #reset playlist
    mpc clear
    mpc load Channels
    mpc play
    ;;
saytitle)
    text=$(mpc | head -n 1)
    mpc toggle
    espeak -ven+f3 -s150 --stdout "$text" | avplay -loglevel quiet -vn -autoexit -nodisp -
    mpc toggle
    ;;
channeldown)
    #'mpc next' removes current track from playlist
    cur=$(mpc | sed 1d | grep '#' | sed 's/^.*#\([0-9]\+\).*/\1/')
    mpc play $((cur+1))
    ;;
channelup)
    mpc prev
    ;;
startcd)
    pgrep abcde && (echo "abcde process already running - aborting"; exit)
    dev=$2
    chmod o+r $dev  # CDROM device has group cdrom and mode 660, but mpd is member of group audio only.
    if [ "$mode" == "rip" ]; then
        # http://wiki.ubuntuusers.de/abcde
        abcde -N -d $dev -x &
    else
        cddb=$(abcde -d $dev -N -a cddb,clean 2>&1)
        echo "$cddb"
        tracks=$(echo "$cddb" | grep -e '^[0-9]\+:')
        #lasttrack=$(cdparanoia -d $dev --query 2>&1 | grep "no   no" | wc -l)
        lasttrack=$(echo "$tracks" | wc -l)
        if [ "$lasttrack" != "0" ]; then
            cur=$(mpc playlist | wc -l)
            #for i in $(seq 1 $lasttrack); do
            #    mpc add cdda://$dev/$i
            #done

            #Generate pls file
            exec 3>&1 # Save current stdout
            exec > /var/lib/mpd/playlists/cd.pls
            echo [playlist]
            echo NumberOfEntries=$lasttrack
            while read track; do
                no=${track/: [^ ]*/}
                title=${track/[0-9]*: /}
                echo
                echo File$no=cdda://$dev/$no
                echo Title$no=$title
                echo Length$no=-1
            done <<<"$tracks"
            exec 1>&3  # Restore stdout
            mpc load cd.pls

            mpc play $((cur+1))
            #mpc volume 100
        fi
    fi
    ;;
removecd)
    # NOTE: mpd hangs when playing track of ejecting CD!
    dev=$2
    cdtracks=$(mpc playlist --format=%file% | grep --line-number cdda://$dev | cut -d : -f 1 | tac)
    for t in $cdtracks; do
        mpc del $t
        #mpc volume 90
    done
    rm -f /var/lib/mpd/playlists/cd.pls
    ;;
cdmode)
    mode=$2
    echo -n $mode >$MODEFILE
    ;;
esac

echo $(date +"%F %T") $* finished
