#!/bin/bash

cmd=$1

case $cmd in
power)
    mpc toggle
    ;;
save)
    #reset playlist
    mpc clear
    mpc load Channels
    mpc play
    ;;
enter)
    text=$(mpc | head -n 1)
    mpc toggle
    espeak -ven+f3 -s150 --stdout "$text" | avplay -loglevel quiet -vn -autoexit -nodisp -
    mpc toggle
    ;;
channeldown)
    #'mpc next' removes current track from playlist
    cur=$(mpc | sed 1d | grep '#' | sed 's/^.*#\([0-9]\+\).*/\1/')
    mpc play $((cur+1))
    ;;
channelup)
    mpc prev
    ;;
volumeup)
    ;;
volumedown)
    ;;
*)
    mpc $cmd
    ;;
esac
